version: '3'
services:
    php:
        image: php:5.6.31-fpm
        restart: always
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www/:/var/www/html
        networks:
            - symfony
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www/:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
        networks:
            - symfony
	    environment:
   	        - NGINX_HOST=hafta3.dev
             - NGINX_PORT=80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/www > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
    symfony:
        driver: bridge
