# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_entity_users:
            entity:
                class: AppBundle:User
                property: userName


    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true

            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            #form_login:
                #use_referer: true

            guard:
                authenticators:
                    - custom_authenticator


            logout:
                path:   /logout
                target: /


    access_control:
    #https'e zorunlu yönledrimek için requires_channel kullandık
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https}
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https}
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https}
            - { path: ^/admin/, role: ROLE_ADMIN , requires_channel: https}
